// Generated by Grafana k6 Studio (1.4.0) on 2025-06-13T01:58:48.730Z

import { browser } from 'k6/browser';
import { expect } from 'https://jslib.k6.io/k6-testing/0.4.0/index.js';

export const options = {
  scenarios: {
    default: {
      executor: 'shared-iterations',
      vus: 5, // Number of virtual users
      iterations: 5, // Number of iterations can't be less than the number of VUs (5)
      options: { browser: { type: 'chromium' } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  await page.goto('https://www.saucedemo.com/');

  await page.locator('#user-name').type('standard_user');

  await page.locator('#password').type('secret_sauce');

  await page.locator('#login-button').click();

  await expect(page.locator('.title')).toHaveText('Products');

  await page.locator('#react-burger-menu-btn').click();

  await expect(page.locator('[data-test="logout-sidebar-link"]')).toBeVisible();

  await page.locator('[data-test="logout-sidebar-link"]').click();
}
